### ISSUE TITLE
forwarding the log data

### ISSUE THREAD

**Issue by christinaKy** [NatLibFi/loglevel-message-buffer#1]
Hello,
Where exactly are the log messages send or saved after log.flush()?

**Comment by ghost** [comment]
To the next plugin or loglevel itself.

**Comment by christinaKy** [comment]
What do you mean? how can I access the data log?

**Comment by ghost** [comment]
If you initialise loglevel with just this plugin:
```js
var log = require('loglevel');
var loglevelMessageBuffer = require('loglevel-message-buffer');

loglevelMessageBuffer(log);

log.warn('TEST');
log.flush();
```

The message is logged only after _#flush_ is called.

If you initialise loglevel with another plugin, it will receive the message only after _#flush_ is called.

```js
var log = require('loglevel');
var loglevelMessageBuffer = require('loglevel-message-buffer');
var arr = [];

// This is a fictious plugin that sends message to an array specified by the second argument
loglevelAppendToArray(log, arr);
loglevelMessageBuffer(log);

log.warn('TEST');
log.flush();
```

Now _arr_ contains one element: 'TEST'.
